events { worker_connections 1024; }

http {
    upstream lab3_servers {
        # Using the Docker Gateway IP to find the other containers
        server 172.17.0.1:8081;
        server 172.17.0.1:8082;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://lab3_servers;
        }
    }
}
