events { worker_connections 1024; }

http {
    upstream myapp {
        # These are the internal Docker IPs or host IP
        server 172.17.0.1:8081;
        server 172.17.0.1:8082;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://myapp;
        }
    }
}
